name: Build Firmware
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Burnmaster-Firmware
        uses: actions/checkout@v2
        with:
          path: Burnmaster-Firmware
          
      - name: Install EmeddedStudio
        run: |
            wget https://dl.a.segger.com/embedded-studio/Setup_EmbeddedStudio_ARM_v730_linux_x64.tar.gz
            tar -xvf Setup_EmbeddedStudio_ARM_v730_linux_x64.tar.gz
            cd arm_segger_embedded_studio_v730_linux_x64/
            sudo ./install_segger_embedded_studio --minimal-install --accept-license --copy-files-to .
        
      - name: Compile Firmware
        run: |
            cd arm_segger_embedded_studio_v730_linux_x64/bin
            ./emBuild -config "Release" ${{ github.workspace }}//Burnmaster-Firmware/GDCartReader.emProject
          
      - uses: actions/upload-artifact@v3
        with:
          name: Burnmaster-Firmware
          path: ${{ github.workspace }}//Burnmaster-Firmware/Output/Release/Exe/GDCartReader.bin